#!/bin/sh

if [ -z "$1" ]; then
    echo "Musisz zadać jakieś pytanie, np: pytaj-mape \"Co mam w notatkach?\""
    exit 1
fi

KONTEKST=$(find ~/mapa -type f ! -name ".*" ! -name "*~" -name "*.org" -exec cat {} +)

echo "Analizuję całą Mapę (RTX 3050)..."

cat << END_OLLAMA | LD_LIBRARY_PATH=/run/opengl-driver/lib:$LD_LIBRARY_PATH ollama run llama3
Jesteś osobistym asystentem. Masz dostęp do moich notatek z folderu mapa, które załączam poniżej. Odpowiedz na pytanie użytkownika, bazując na tych informacjach. Odpowiedz WYŁĄCZNIE po polsku.

--- NOTATKI ---
$KONTEKST
---

Pytanie: $*
END_OLLAMA